### ISSUE TITLE
I have a queston!

### ISSUE THREAD

**Issue by lbwang1234** [AI-Chen/Deeplab-v3-Plus-pytorch-#1]
dataset文件夹层次是什么
请问train_path_list.csv写入的是什么

**Comment by lbwang1234** [comment]
还有这个.csv文件是怎么生成的？
谢谢！

**Comment by AI-Chen** [comment]
> 还有这个.csv文件是怎么生成的？
> 谢谢！

我在readme中更新了对这个文件的阐述。

**Comment by lbwang1234** [comment]
thanks for your reply.
when I train the network ,I meet some problem ,could you help me?
it is
 hpc@hpc-Workstation:~/wlb/Deeplab-v3-Plus-pytorch--master$ python deeplab_v3p_train.py 
/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/hpc/wlb/Deeplab-v3-Plus-pytorch--master/utils/data_utils.py:17: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  imgs.append((data.ix[i,1], data.ix[i,2]))
/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/pandas/core/indexing.py:961: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  return getattr(section, self.name)[new_key]
Traceback (most recent call last):
  File "deeplab_v3p_train.py", line 50, in <module>
    train_data = Mydataset(path=args.train_path,transform=transform)
  File "/home/hpc/wlb/Deeplab-v3-Plus-pytorch--master/utils/data_utils.py", line 17, in __init__
    imgs.append((data.ix[i,1], data.ix[i,2]))
  File "/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/pandas/core/indexing.py", line 142, in __getitem__
    return self._getitem_tuple(key)
  File "/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/pandas/core/indexing.py", line 805, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/pandas/core/indexing.py", line 961, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
  File "/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/pandas/core/indexing.py", line 148, in __getitem__
    return self._getitem_axis(key, axis=axis)
  File "/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/pandas/core/indexing.py", line 1038, in _getitem_axis
    return self._get_loc(key, axis=axis)
  File "/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/pandas/core/indexing.py", line 163, in _get_loc
    return self.obj._ixs(key, axis=axis)
  File "/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/pandas/core/series.py", line 1056, in _ixs
    return libindex.get_value_at(values, i)
  File "pandas/_libs/index.pyx", line 42, in pandas._libs.index.get_value_at
  File "pandas/_libs/index.pyx", line 47, in pandas._libs.index.get_value_at
  File "pandas/_libs/util.pxd", line 98, in pandas._libs.util.get_value_at
  File "pandas/_libs/util.pxd", line 89, in pandas._libs.util.validate_indexer
IndexError: index out of bounds

**Comment by AI-Chen** [comment]
> thanks for your reply.
> when I train the network ,I meet some problem ,could you help me?
> it is
> hpc@hpc-Workstation:~/wlb/Deeplab-v3-Plus-pytorch--master$ python deeplab_v3p_train.py
> /home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> /home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> /home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> /home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> /home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> /home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> np_resource = np.dtype([("resource", np.ubyte, 1)])
> /home/hpc/wlb/Deeplab-v3-Plus-pytorch--master/utils/data_utils.py:17: FutureWarning:
> .ix is deprecated. Please use
> .loc for label based indexing or
> .iloc for positional indexing
> 
> See the documentation here:
> http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
> imgs.append((data.ix[i,1], data.ix[i,2]))
> /home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/pandas/core/indexing.py:961: FutureWarning:
> .ix is deprecated. Please use
> .loc for label based indexing or
> .iloc for positional indexing
> 
> See the documentation here:
> http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
> return getattr(section, self.name)[new_key]
> Traceback (most recent call last):
> File "deeplab_v3p_train.py", line 50, in
> train_data = Mydataset(path=args.train_path,transform=transform)
> File "/home/hpc/wlb/Deeplab-v3-Plus-pytorch--master/utils/data_utils.py", line 17, in **init**
> imgs.append((data.ix[i,1], data.ix[i,2]))
> File "/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/pandas/core/indexing.py", line 142, in **getitem**
> return self._getitem_tuple(key)
> File "/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/pandas/core/indexing.py", line 805, in _getitem_tuple
> return self._getitem_lowerdim(tup)
> File "/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/pandas/core/indexing.py", line 961, in _getitem_lowerdim
> return getattr(section, self.name)[new_key]
> File "/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/pandas/core/indexing.py", line 148, in **getitem**
> return self._getitem_axis(key, axis=axis)
> File "/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/pandas/core/indexing.py", line 1038, in _getitem_axis
> return self._get_loc(key, axis=axis)
> File "/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/pandas/core/indexing.py", line 163, in _get_loc
> return self.obj._ixs(key, axis=axis)
> File "/home/hpc/anaconda3/envs/wlbwork/lib/python3.6/site-packages/pandas/core/series.py", line 1056, in _ixs
> return libindex.get_value_at(values, i)
> File "pandas/_libs/index.pyx", line 42, in pandas._libs.index.get_value_at
> File "pandas/_libs/index.pyx", line 47, in pandas._libs.index.get_value_at
> File "pandas/_libs/util.pxd", line 98, in pandas._libs.util.get_value_at
> File "pandas/_libs/util.pxd", line 89, in pandas._libs.util.validate_indexer
> IndexError: index out of bounds

你的csv文件时自己是自己处理数据生成的嘛

**Comment by lbwang1234** [comment]
是我自己生成的，它的形式是：两列，第一列是原图像的绝对路径，第二列是标签的绝对路径
不应该是这样么

**Comment by AI-Chen** [comment]
> 是我自己生成的，它的形式是：两列，第一列是原图像的绝对路径，第二列是标签的绝对路径
> 不应该是这样么

那你把data.ix[i,1], data.ix[i,2]改为data.ix[i,0], data.ix[i,1]

**Comment by lbwang1234** [comment]
哦哦，谢谢大佬，我试试

**Comment by neverstoplearn** [comment]
> 哦哦，谢谢大佬，我试试

你好  请问可以分享一下你下载的数据集吗？我这里通过ftp下载非常缓慢，非常感谢！
